Repository nihruk/design-system, pull requests merged in 2023-03, with the labels that each got.

#46 Add the NIHR logo to the documentation site
  src/partials/header/header-with-search.html
  src/partials/header/header.html
Labels: enhancement

#47 Do not use the search component for the documentation site itself
  src/html/index.html
Labels: enhancement

#48 Remove all links to Confluence as part of its deprecation for the Design System
  src/html/index.html
  src/html/pages/alerts.html
  src/html/pages/buttons.html
  src/html/pages/explore-other-sites.html
  src/html/pages/footer.html
  src/html/pages/header.html
  src/html/pages/nihr-newsletter.html
  src/html/pages/search-components.html
  src/html/pages/search-elements.html
  src/html/pages/search-filters.html
  src/html/pages/typography.html
  src/partials/header/navbar.html
Labels: enhancement

#49 Remove the 'Explore other sites' and 'Newletter' components from the front page
  src/html/index.html
Labels: enhancement

#50 Update the primary navigation links
  src/partials/header/navbar.html
Labels: enhancement

#51 Update the project name
  README.md
  package.json
  src/html/index.html
  src/partials/header/navbar.html
Labels: enhancement, BC break

#52 Update the footer and show it on all pages
  src/html/index.html
  src/html/pages/alerts.html
  src/html/pages/buttons.html
  src/html/pages/explore-other-sites.html
  src/html/pages/footer.html
  src/html/pages/forms.html
  src/html/pages/grid.html
  src/html/pages/header.html
  src/html/pages/nihr-newsletter.html
  src/html/pages/search-components.html
  src/html/pages/search-elements.html
  src/html/pages/search-filters.html
  src/html/pages/typography.html
  src/partials/footer/footer.html
Labels: enhancement

#53 Add an 'About us' page
  src/html/about-us/index.html
  src/partials/header/navbar.html
Labels: enhancement

#54 Add a favicon to the documentation site
  src/partials/header/head.html
Labels: enhancement

#56 Add and update the project homepage
  README.md
  package.json
Labels: bug, enhancement

#57 Fix some of the npm scripts command usage, as it was not compatible with Windows
  .github/workflows/test.yml
  package.json
Labels: bug

#58 Remove Node.js 16 support, and add Node.js 19 support
  .github/workflows/test.yml
  README.md
  package.json
Labels: enhancement

#40 Add Responsive Font Size (RFS) for deskop viewports
  src/assets/scss/theme.scss
Labels: enhancement

#61 Replace usage of Github Actions' deprecated set-output with environment variables
  .github/workflows/test.yml
Labels: bug

#64 Include assets in npm releases, part 2
  .github/workflows/release-new-version.yml
Labels: enhancement

#75 Add the missing terser-webpack-plugin dependency
  package.json
Labels: bug

#80 Simplify the Webpack configuration
  package.json
  webpack.config.js
Labels: enhancement

#81 Produce CSS bundles that meet the browser support requirements
  package.json
  webpack.config.js
Labels: bug

#82 Transpile JavaScript to ensure it meets browser support requirements
  webpack.config.js
Labels: bug

#85 Remove an unused Webpack optimization
  webpack.config.js
Labels: enhancement

#67 Bundle the Lato and Font Awesome Free fonts with the Design System
  package.json
  src/assets/scss/abstracts/variables/_typography.scss
  src/partials/header/head.html
  webpack.config.js
Labels: enhancement

#86 Remove unused dependencies
  package.json
Labels: enhancement

#92 Remove all references to specific NIHR services that are not mere examples
  src/docs/www/_docs_assets/images/component/header/header-main-corporate.png
  src/docs/www/_docs_assets/images/component/header/header-main-funding and awards.png
  src/docs/www/_docs_assets/images/component/header/header-main-journals library.png
  src/docs/www/_docs_assets/images/component/search-bar/corporate.png
  src/docs/www/_docs_assets/images/component/search-bar/fa.png
  src/docs/www/_docs_assets/images/component/search-bar/jl.png
  src/docs/www/component/explore/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/search-bar/index.html
Labels: bug, enhancement

#96 Remove the newsletter component, because it is not reusable
  src/assets/scss/components/_components.scss
  src/assets/scss/components/_nihr-newsletter.scss
  src/docs/partials/component/newsletter/nihr-newsletter.html
  src/docs/www/_docs_assets/images/component/footer/footer-corporate.png
  src/docs/www/component/footer/index.html
  src/docs/www/component/index.html
  src/docs/www/component/newsletter/index.html
Labels: enhancement, BC break

#95 Fix placeholder images and remove motifs
  src/assets/scss/components/_explore-our-other-sites.scss
  src/docs/partials/component/footer/footer-component.html
  src/docs/www/_docs_assets/images/component/explore/all cards.png
  src/docs/www/component/explore/index.html
Labels: enhancement

#97 Convert the table with colors to a table, and remove the inaccessible original image
  src/docs/partials/cmyk-specifications.html
  src/docs/partials/color-specification.html
  src/docs/partials/header/head.html
  src/docs/partials/hex-specifications.html
  src/docs/partials/pantone-specifications.html
  src/docs/partials/rgb-specifications.html
  src/docs/www/_docs_assets/images/brand-and-identity/colour/image-20230117-150531.png
  src/docs/www/brand-and-identity/colour/index.html
Labels: enhancement

#99 Remove component images and Zeplin links
  src/docs/www/_docs_assets/images/component/form/image-20221129-123150.png
  src/docs/www/_docs_assets/images/component/form/image-20221129-123544.png
  src/docs/www/_docs_assets/images/component/search-bar/5-search results page.png
  src/docs/www/_docs_assets/images/component/search-bar/6- advanced search.png
  src/docs/www/_docs_assets/images/component/search-filter/0d741ab9-f957-4717-89e8-f119e420dad5.png
  src/docs/www/_docs_assets/images/component/search-filter/image-20220908-072436.png
  src/docs/www/_docs_assets/images/component/select-input/select.png
  src/docs/www/_docs_assets/images/component/table/image-20220908-092342.png
  src/docs/www/_docs_assets/images/component/text-input/image-20220908-075027.png
  src/docs/www/brand-and-identity/text/index.html
  src/docs/www/component/alert/index.html
  src/docs/www/component/button/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/explore/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/search-bar/index.html
  src/docs/www/component/search-filter/index.html
  src/docs/www/component/search-input/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/table/index.html
  src/docs/www/component/text-input/index.html
Labels: bug, enhancement

#100 Remove the docs for the non-existent Forms component
  src/docs/www/component/form/index.html
Labels: enhancement

#101 Replace Handlebars with Nunjucks
  package.json
  src/docs/partials/cmyk-specifications.html
  src/docs/partials/color-specification.html
  src/docs/partials/component/search-bar/lg-search-component-fa.html
  src/docs/partials/component/search-bar/lg-search-component-jl.html
  src/docs/partials/component/search-bar/lg-search-inner-page-component.html
  src/docs/partials/footer.html
  src/docs/partials/header/head.html
  src/docs/partials/header/header-with-search.html
  src/docs/partials/hex-specifications.html
  src/docs/partials/page.html
  src/docs/partials/pantone-specifications.html
  src/docs/partials/rgb-specifications.html
  src/docs/www/about-us/index.html
  src/docs/www/brand-and-identity/colour/index.html
  src/docs/www/brand-and-identity/index.html
  src/docs/www/brand-and-identity/text/index.html
  src/docs/www/brand-and-identity/typography/index.html
  src/docs/www/component/alert/index.html
  src/docs/www/component/button/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/explore/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/index.html
  src/docs/www/component/search-bar/index.html
  src/docs/www/component/search-filter/index.html
  src/docs/www/component/search-input/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/table/index.html
  src/docs/www/component/text-input/index.html
  src/docs/www/design/index.html
  src/docs/www/design/layout/index.html
  src/docs/www/index.html
  webpack.config.js
Labels: enhancement, BC break

#102 Show code for all examples
  handlebars.js
  package.json
  src/assets/scss/theme.scss
  src/docs/partials/example.html
  src/docs/partials/header/head.html
  src/docs/partials/html-example.html
  src/docs/scss/main.scss
  src/docs/www/brand-and-identity/text/index.html
  src/docs/www/brand-and-identity/typography/index.html
  src/docs/www/component/alert/index.html
  src/docs/www/component/button/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/explore/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/search-bar/index.html
  src/docs/www/component/search-filter/index.html
  src/docs/www/component/search-input/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/text-input/index.html
  src/docs/www/design/layout/index.html
  webpack.config.js
Labels: enhancement

#104 Remove external links icons
  src/docs/partials/component/explore/explore-other-sites.html
  src/docs/partials/design/layout/layouts-component.html
Labels: bug, enhancement

#105 Remove more unneeded references to specific NIHR services
  src/docs/www/component/header/index.html
Labels: bug, enhancement

#98 Document the secondary colors
  src/docs/www/brand-and-identity/colour/index.html
Labels: enhancement

#107 Convert the images in the layout documentation to HTML
  src/docs/partials/design/layout/layouts-component.html
  src/docs/partials/design/layout/two-thirds--one-third.html
  src/docs/partials/design/layout/two-thirds.html
  src/docs/www/_docs_assets/images/design/layout/334a0b06-6caa-46ed-936c-0d520a9f2c22.png
  src/docs/www/_docs_assets/images/design/layout/5273c35f-1b1a-4260-b93e-3a09d9127173.png
  src/docs/www/_docs_assets/images/design/layout/5e12f042-951d-4dfd-acc8-03069280f894.png
  src/docs/www/design/layout/index.html
Labels: bug, enhancement

#108 Mark links on the documentation site to the current or an ancestor page as active
  src/docs/partials/header/navbar.html
  webpack.config.js
Labels: enhancement

#106 Update the text types
  src/docs/www/_docs_assets/images/brand-and-identity/text/733c2418-270d-474e-b0e6-5d5c8be923f3.png
  src/docs/www/_docs_assets/images/brand-and-identity/text/7d5f26a4-d6e4-4408-b520-817272150e2e.png
  src/docs/www/brand-and-identity/index.html
  src/docs/www/brand-and-identity/text/index.html
Labels: bug, enhancement

#109 Add component navigation to the documentation site
  src/docs/partials/component-list.html
  src/docs/partials/component-page.html
  src/docs/partials/page.html
  src/docs/www/about-us/index.html
  src/docs/www/brand-and-identity/colour/index.html
  src/docs/www/brand-and-identity/index.html
  src/docs/www/brand-and-identity/text/index.html
  src/docs/www/brand-and-identity/typography/index.html
  src/docs/www/component/alert/index.html
  src/docs/www/component/button/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/explore/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/index.html
  src/docs/www/component/search-bar/index.html
  src/docs/www/component/search-filter/index.html
  src/docs/www/component/search-input/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/table/index.html
  src/docs/www/component/text-input/index.html
  src/docs/www/design/index.html
  src/docs/www/design/layout/index.html
  src/docs/www/index.html
Labels: enhancement

#113 Consolidate Brand and Identity and Design into a new Styles section.
  src/docs/partials/header/navbar.html
  src/docs/partials/style-list.html
  src/docs/partials/style-page.html
  src/docs/partials/style/layout/two-thirds--one-third.html
  src/docs/partials/style/layout/two-thirds.html
  src/docs/partials/style/typography/typography.html
  src/docs/www/_docs_assets/images/style/typography/1.png
  src/docs/www/_docs_assets/images/style/typography/line heights.png
  src/docs/www/_docs_assets/images/style/typography/paragraphs.png
  src/docs/www/_docs_assets/images/style/typography/scale.png
  src/docs/www/brand-and-identity/index.html
  src/docs/www/design/index.html
  src/docs/www/style/colour/index.html
  src/docs/www/style/index.html
  src/docs/www/style/layout/index.html
  src/docs/www/style/text/index.html
  src/docs/www/style/typography/index.html
Labels: enhancement
