Repository nihruk/design-system, pull requests merged in 2023-07, with the labels that each got.

#202 Fix broken and inconsistent Nunjucks example code
  src/docs/www/component/action-link/index.html
  src/docs/www/component/callout-text/index.html
  src/docs/www/component/card/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/search/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/table/index.html
Labels: bug, enhancement

#187 Heroes
  src/assets/scss/abstracts/variables/_cards.scss
  src/assets/scss/components/_components.scss
  src/assets/scss/components/_hero.scss
  src/docs/partials/component-navigation.html
  src/docs/www/component/hero/index.html
  src/macros/component/hero.html
Labels: enhancement

#206 Search needs a label
  src/macros/component/search.html
Labels: a11y

#210 Hero typo
  src/macros/component/hero.html
Labels: enhancement, good first issue
