Repository nihruk/design-system, pull requests merged in 2023-08, with the labels that each got.

#231 Default font size for tables
  src/assets/scss/theme.scss
Labels: enhancement

#230 Responsive tables
  src/docs/www/component/table/index.html
  src/macros/component/table.html
Labels: documentation, enhancement

#232 Constrain the content width on the about page to improve readability
  src/docs/partials/component-page.html
  src/docs/partials/get-started-page.html
  src/docs/partials/style-page.html
  src/docs/partials/style/layout/two-thirds--one-third.html
  src/docs/partials/style/layout/two-thirds.html
  src/docs/www/about-us/index.html
  src/docs/www/get-started/install/index.html
  src/docs/www/index.html
Labels: enhancement

#236 Allow tables to receive additional HTML attributes.
  src/docs/js/nunjucks.js
  src/macros/component/table.html
Labels: enhancement

#150 Make the color style documentation responsive
  src/assets/scss/abstracts/variables/_colour.scss
  src/assets/scss/abstracts/variables/_typography.scss
  src/docs/js/nunjucks.js
  src/docs/macros/component/colour-card.html
  src/docs/macros/component/colour-specification.html
  src/docs/macros/component/example.html
  src/docs/scss/main.scss
  src/docs/www/style/colour/all-colours/index.html
  src/docs/www/style/colour/index.html
  src/macros/component/accordion.html
  src/macros/component/card.html
Labels: enhancement

#115 Document borders
  src/docs/partials/style-navigation.html
  src/docs/www/style/border/index.html
Labels: enhancement

#240 Document the Design System's accessibility
  src/docs/macros/component/colour-specification.html
  src/docs/partials/page.html
  src/docs/www/accessibility/index.html
  src/docs/www/style/colour/index.html
Labels: documentation, enhancement

#239 Fix a bug where the value of aria-current HTML attributes would be invalid
  src/docs/js/nunjucks.js
  src/docs/partials/secondary-navigation.html
Labels: bug

#247 Adding link to service header
  src/macros/component/header.html
Labels: enhancement

#237 Removing h1 from page component
  src/docs/partials/component-page.html
  src/docs/partials/get-started-page.html
  src/docs/partials/style-page.html
  src/docs/www/about-us/index.html
  src/docs/www/accessibility/index.html
  src/docs/www/component/card/index.html
  src/docs/www/component/hero/index.html
  src/docs/www/index.html
  src/docs/www/style/icon/index.html
  src/macros/component/page.html
Labels: enhancement

#249 Use the card() macro in Hero component examples
  src/assets/scss/abstracts/variables/_card.scss
  src/docs/www/component/hero/index.html
  src/macros/component/card.html
  src/macros/component/hero.html
Labels: enhancement

#251 Fix a grid bug on the All colours page
  src/docs/www/style/colour/all-colours/index.html
Labels: bug

#252 Patch the primary navigation link font size
  src/assets/scss/components/_main-navigation.scss
Labels: enhancement

#254 Fix the documentation site title
  src/docs/partials/page.html
  src/docs/www/index.html
  src/macros/component/page.html
Labels: enhancement

#253 Implement the Hero and Card components on the documentation site's own front page
  src/docs/macros/component/colour-card.html
  src/docs/www/component/card/index.html
  src/docs/www/component/hero/index.html
  src/docs/www/index.html
  src/macros/component/card.html
  src/macros/component/hero.html
Labels: enhancement

#242 Add coral underlines to headings
  src/assets/scss/abstracts/variables/_colour.scss
  src/assets/scss/theme.scss
  src/docs/www/about-us/index.html
  src/docs/www/accessibility/index.html
  src/docs/www/component/accordion/index.html
  src/docs/www/component/action-link/index.html
  src/docs/www/component/button/index.html
  src/docs/www/component/callout-text/index.html
  src/docs/www/component/card/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/hero/index.html
  src/docs/www/component/page/index.html
  src/docs/www/component/search/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/table/index.html
  src/docs/www/component/text-input/index.html
  src/docs/www/get-started/install/hosted/index.html
  src/docs/www/get-started/install/index.html
  src/docs/www/get-started/install/npm/index.html
  src/docs/www/index.html
  src/docs/www/style/border/index.html
  src/docs/www/style/colour/all-colours/index.html
  src/docs/www/style/colour/index.html
  src/docs/www/style/icon/index.html
  src/docs/www/style/layout/index.html
  src/docs/www/style/text/index.html
  src/docs/www/style/typography/index.html
  src/macros/component/card.html
Labels: enhancement

#256 Examples to Variations
  src/docs/www/component/action-link/index.html
  src/docs/www/component/callout-text/index.html
  src/docs/www/component/card/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/header/index.html
  src/docs/www/component/hero/index.html
  src/docs/www/component/page/index.html
  src/docs/www/component/search/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/table/index.html
  src/docs/www/component/text-input/index.html
Labels: documentation, enhancement, good first issue

#259 Fix a bug where the distribution files could not be used on all websites
  webpack.config.js
Labels: bug

#257 Filler text
  src/docs/www/component/accordion/index.html
  src/docs/www/component/callout-text/index.html
  src/docs/www/component/checkbox/index.html
  src/docs/www/component/footer/index.html
  src/docs/www/component/hero/index.html
  src/docs/www/component/select-input/index.html
  src/docs/www/component/text-input/index.html
Labels: documentation, enhancement, good first issue

#261 Rename the Search Input to Search Form
  src/assets/scss/components/_components.scss
  src/assets/scss/components/_main-header.scss
  src/assets/scss/components/_search-form.scss
  src/docs/partials/component-navigation.html
  src/docs/www/component/header/index.html
  src/docs/www/component/search-form/index.html
  src/macros/component/header.html
  src/macros/component/search-form.html
Labels: enhancement, BC break

#258 Fix layout spacing bugs
  src/assets/scss/components/_hero.scss
  src/docs/partials/component-page.html
  src/docs/partials/get-started-page.html
  src/docs/partials/style-page.html
  src/docs/www/about-us/index.html
  src/docs/www/accessibility/index.html
  src/docs/www/component/page/index.html
  src/docs/www/index.html
  src/macros/component/page.html
Labels: bug, BC break

#260 Subdivide component navigation
  src/docs/partials/component-navigation.html
  src/docs/partials/get-started-navigation.html
  src/docs/partials/secondary-navigation.html
Labels: enhancement

#243 Add a Hero Search design pattern
  src/assets/scss/components/_hero.scss
  src/docs/partials/page.html
  src/docs/partials/pattern-navigation.html
  src/docs/partials/pattern-page.html
  src/docs/www/component/hero/index.html
  src/docs/www/component/search-form/index.html
  src/docs/www/get-started/index.html
  src/docs/www/pattern/hero-search/index.html
  src/docs/www/pattern/index.html
  src/macros/component/hero.html
Labels: enhancement

#255 Allow Cards to only show images, and make them fit the entire Card
  src/assets/scss/abstracts/variables/_card.scss
  src/macros/component/card.html
Labels: bug

#265 Adding h1 to Pattern
  src/docs/partials/pattern-page.html
Labels: a11y

#266 Patterns page padding
  src/docs/www/pattern/index.html
Labels: enhancement

#267 Introduce the Design System Nunjucks API
  src/assets/js/nunjucks.js
  src/docs/js/nunjucks.js
  src/docs/partials/page.html
  src/docs/www/component/page/index.html
  src/macros/component/footer.html
  src/macros/component/page.html
Labels: enhancement, BC break

#268 Documentation - Accordion
  src/docs/www/component/accordion/index.html
Labels: documentation

#270 Documentation Cards
  src/docs/www/component/card/index.html
Labels: documentation

#269 Documentation Callout Text
  src/docs/www/component/callout-text/index.html
Labels: documentation

#250 Adding correct focus states
  src/assets/scss/components/_accordion.scss
  src/assets/scss/components/_action-link.scss
  src/assets/scss/components/_components.scss
  src/assets/scss/components/_footer.scss
  src/assets/scss/components/_main-header.scss
  src/assets/scss/components/_main-navigation.scss
  src/assets/scss/components/_secondary-navigation.scss
  src/assets/scss/theme.scss
  src/macros/component/footer.html
  src/macros/component/header.html
Labels: enhancement, a11y

#277 Fix empty HTML attributes being rendered needlessly by the Nunjucks environment
  src/assets/js/nunjucks.js
Labels: enhancement

#276 Simplify the text types documentation
  src/docs/www/style/text/index.html
Labels: documentation, enhancement, BC break
