Repository nihruk/design-system, pull requests merged in 2023-06, with the labels that each got.

#188 lead font values
  src/assets/scss/abstracts/variables/_typography.scss
  src/assets/scss/theme.scss
Labels: enhancement

#191 Apply the Action Link to the documentation site
  src/docs/www/component/index.html
  src/docs/www/index.html
  src/macros/component/action-link.html
Labels: enhancement

#193 Remove the Explore component
  src/assets/scss/components/_components.scss
  src/assets/scss/components/_explore.scss
  src/docs/partials/component-navigation.html
  src/docs/www/component/explore/index.html
  src/macros/component/explore.html
Labels: enhancement, BC break

#192 Remove the Alert component
  src/assets/scss/theme.scss
  src/docs/partials/component-navigation.html
  src/docs/www/component/alert/index.html
  src/macros/component/alert.html
Labels: enhancement, BC break

#198 Remove the redundant link title from the Footer component's social media link icons
  src/macros/component/footer.html
Labels: enhancement, a11y
